[package]
name = "kang"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
urlencoding = "2.1.3"
